"use strict";
const test = require("node:test"), assert = require("node:assert/strict"), Core = require("../web/online-core");

function playingRoom() {
  let room = Core.createOnlineRoom({ code: "AB12CD", hostName: "Ali", settings: { gameType: "clubs" }, now: 100 });
  room = Core.joinOnlineRoom(room, { playerName: "Ece", expectedVersion: room.stateVersion, now: 101 });
  room = Core.setOnlineReady(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 102 });
  room = Core.setOnlineReady(room, { playerIndex: 1, expectedVersion: room.stateVersion, now: 103 });
  room = Core.startOnlineGame(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 104 });
  return Core.publishOnlineQuestion(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 105, question: { questionId: "q1", optionPlayerIds: [10, 11, 12, 13], correctPlayerId: 10 } });
}

test("kısa oda kodu güvenli alfabe ile üretilir", () => assert.match(Core.generateRoomCode(Uint8Array.from([0, 1, 2, 3, 4, 5])), /^[A-HJ-NP-Z2-9]{6}$/));
test("oda koduyla oyuncu doğru odaya katılır", () => { const room = Core.createOnlineRoom({ code: "AB12CD", settings: {}, now: 0 }); const joined = Core.joinOnlineRoom(room, { playerName: "Ece", expectedVersion: 1, now: 1 }); assert.equal(joined.players[1].name, "Ece"); });
test("oda beş oyuncuya kadar katılım kabul eder", () => { let room = Core.createOnlineRoom({ code: "AB12CD", settings: {}, now: 0 }); for (let i = 1; i < 5; i++) room = Core.joinOnlineRoom(room, { playerName: `P${i + 1}`, expectedVersion: room.stateVersion, now: i }); assert.equal(room.players.length, 5); assert.throws(() => Core.joinOnlineRoom(room, { expectedVersion: room.stateVersion, now: 6 }), /ROOM_FULL/); });
test("oyuncular cevaplarını birbirinden bağımsız verir", () => { const next = Core.submitOnlineAnswer(playingRoom(), { playerIndex: 1, questionId: "q1", selectedPlayerId: 10, expectedVersion: 6, now: 106 }); assert.equal(next.roundAnswers[1].result, "correct"); assert.equal(next.revealUntil, null); });
test("son oyuncu cevap verene kadar sonuç açıklanmaz", () => { let room = playingRoom(); room = Core.submitOnlineAnswer(room, { playerIndex: 0, questionId: "q1", selectedPlayerId: 11, expectedVersion: room.stateVersion, now: 106 }); assert.equal(room.answerResult, null); room = Core.submitOnlineAnswer(room, { playerIndex: 1, questionId: "q1", selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 107 }); assert.equal(room.answerResult, "revealed"); assert.equal(room.revealUntil, 2107); });
test("aynı oyuncu aynı soruyu iki kez cevaplayamaz", () => { const room = playingRoom(); const answered = Core.submitOnlineAnswer(room, { playerIndex: 0, questionId: "q1", selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 106 }); assert.throws(() => Core.submitOnlineAnswer(answered, { playerIndex: 0, questionId: "q1", selectedPlayerId: 10, expectedVersion: answered.stateVersion, now: 107 }), /QUESTION_ALREADY_ANSWERED/); });
test("oyun bitince host aynı odada yeni oyun seçebilir", () => { let room = playingRoom(); room = Core.submitOnlineAnswer(room, { playerIndex: 0, questionId: "q1", selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 106 }); room = Core.submitOnlineAnswer(room, { playerIndex: 1, questionId: "q1", selectedPlayerId: 11, expectedVersion: room.stateVersion, now: 107 }); room = Core.finishOnlineGame(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 108 }); room = Core.configureOnlineMatch(room, { playerIndex: 0, settings: { gameType: "country", rounds: 5 }, expectedVersion: room.stateVersion, now: 109 }); assert.equal(room.status, "waiting"); assert.equal(room.settings.gameType, "country"); assert.ok(room.players.every((player) => !player.ready)); });
test("güncel olmayan sürüm yeni state'i ezemez", () => assert.throws(() => Core.setOnlineReady(playingRoom(), { playerIndex: 0, expectedVersion: 1, now: 106 }), /STALE_STATE/));
test("bağlantı sonrası güncel state yeniden alınabilir", () => { const room = playingRoom(); const offline = Core.updateConnection(room, { playerIndex: 1, connected: false, expectedVersion: room.stateVersion, now: 106 }); const back = Core.updateConnection(offline, { playerIndex: 1, connected: true, expectedVersion: offline.stateVersion, now: 107 }); assert.equal(back.players[1].connected, true); });
test("süresi dolmuş oda kullanılamaz", () => { const room = Core.createOnlineRoom({ settings: {}, now: 0 }); assert.equal(Core.isRoomExpired(room, Core.ROOM_TTL_MS), true); });
