"use strict";
const test = require("node:test"), assert = require("node:assert/strict"), Core = require("../web/online-core");

function playingRoom() {
  let room = Core.createOnlineRoom({ code: "AB12CD", hostName: "Ali", settings: { gameType: "clubs" }, now: 100 });
  room = Core.joinOnlineRoom(room, { playerName: "Ece", expectedVersion: room.stateVersion, now: 101 });
  room = Core.setOnlineReady(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 102 });
  room = Core.setOnlineReady(room, { playerIndex: 1, expectedVersion: room.stateVersion, now: 103 });
  room = Core.startOnlineGame(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 104 });
  return Core.publishOnlineQuestion(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 105, question: { questionId: "q1", optionPlayerIds: [10, 11, 12, 13], correctPlayerId: 10 } });
}

test("kısa oda kodu güvenli alfabe ile üretilir", () => assert.match(Core.generateRoomCode(Uint8Array.from([0, 1, 2, 3, 4, 5])), /^[A-HJ-NP-Z2-9]{6}$/));
test("oda koduyla oyuncu doğru odaya katılır", () => { const room = Core.createOnlineRoom({ code: "AB12CD", settings: {}, now: 0 }); const joined = Core.joinOnlineRoom(room, { playerName: "Ece", expectedVersion: 1, now: 1 }); assert.equal(joined.players[1].name, "Ece"); });
test("oda beş oyuncuya kadar katılım kabul eder", () => { let room = Core.createOnlineRoom({ code: "AB12CD", settings: {}, now: 0 }); for (let i = 1; i < 5; i++) room = Core.joinOnlineRoom(room, { playerName: `P${i + 1}`, expectedVersion: room.stateVersion, now: i }); assert.equal(room.players.length, 5); assert.throws(() => Core.joinOnlineRoom(room, { expectedVersion: room.stateVersion, now: 6 }), /ROOM_FULL/); });
test("oyun yalnız hazır oyuncularla başlar ve hazır olmayan odada kalır", () => { let room = Core.createOnlineRoom({ code: "AB12CD", hostName: "Host", settings: {}, now: 0 }); room = Core.joinOnlineRoom(room, { playerName: "Hazır", expectedVersion: room.stateVersion, now: 1 }); room = Core.joinOnlineRoom(room, { playerName: "İzleyici", expectedVersion: room.stateVersion, now: 2 }); room = Core.setOnlineReady(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 3 }); room = Core.setOnlineReady(room, { playerIndex: 1, expectedVersion: room.stateVersion, now: 4 }); room = Core.startOnlineGame(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 5 }); assert.deepEqual(room.matchPlayers.map((player) => player.name), ["Host", "Hazır"]); assert.equal(room.players.length, 3); room = Core.publishOnlineQuestion(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 6, question: { questionId: "q", correctPlayerId: 10 } }); assert.throws(() => Core.submitOnlineAnswer(room, { playerIndex: 2, questionId: "q", selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 7 }), /NOT_IN_MATCH/); });
test("üç kişilik maçtan ayrılan oyuncu odada kalırken iki kişi devam eder", () => { let room = Core.createOnlineRoom({ code: "AB12CD", hostName: "H", settings: {}, now: 0 }); for (const name of ["A", "B"]) room = Core.joinOnlineRoom(room, { playerName: name, expectedVersion: room.stateVersion, now: room.stateVersion }); for (let i = 0; i < 3; i++) room = Core.setOnlineReady(room, { playerIndex: i, expectedVersion: room.stateVersion, now: 4 + i }); room = Core.startOnlineGame(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 8 }); room = Core.leaveOnlineMatch(room, { playerIndex: 2, expectedVersion: room.stateVersion, now: 9 }); assert.equal(room.status, "playing"); assert.deepEqual(room.matchPlayers.map((player) => player.name), ["H", "A"]); assert.equal(room.players.length, 3); });
test("iki kişilik maçta ayrılma ve oda sahibinin ayrılması herkesi lobiye döndürür", () => { let room = playingRoom(); room = Core.leaveOnlineMatch(room, { playerIndex: 1, expectedVersion: room.stateVersion, now: 106 }); assert.equal(room.status, "finished"); assert.equal(room.matchResults[0], 0); room = playingRoom(); room = Core.leaveOnlineMatch(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 106 }); assert.equal(room.status, "finished"); });
test("oyuncular cevaplarını birbirinden bağımsız verir", () => { const next = Core.submitOnlineAnswer(playingRoom(), { playerIndex: 1, questionId: "q1", selectedPlayerId: 10, expectedVersion: 6, now: 106 }); assert.equal(next.roundAnswers[1].result, "correct"); assert.equal(next.revealUntil, null); });
test("son oyuncu cevap verene kadar sonuç açıklanmaz", () => { let room = playingRoom(); room = Core.submitOnlineAnswer(room, { playerIndex: 0, questionId: "q1", selectedPlayerId: 11, expectedVersion: room.stateVersion, now: 106 }); assert.equal(room.answerResult, null); room = Core.submitOnlineAnswer(room, { playerIndex: 1, questionId: "q1", selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 107 }); assert.equal(room.answerResult, "revealed"); assert.equal(room.revealUntil, 2107); });
test("aynı oyuncu aynı soruyu iki kez cevaplayamaz", () => { const room = playingRoom(); const answered = Core.submitOnlineAnswer(room, { playerIndex: 0, questionId: "q1", selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 106 }); assert.throws(() => Core.submitOnlineAnswer(answered, { playerIndex: 0, questionId: "q1", selectedPlayerId: 10, expectedVersion: answered.stateVersion, now: 107 }), /QUESTION_ALREADY_ANSWERED/); });
test("oyun bitince host aynı odada yeni oyun seçebilir", () => { let room = playingRoom(); room = Core.submitOnlineAnswer(room, { playerIndex: 0, questionId: "q1", selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 106 }); room = Core.submitOnlineAnswer(room, { playerIndex: 1, questionId: "q1", selectedPlayerId: 11, expectedVersion: room.stateVersion, now: 107 }); room = Core.finishOnlineGame(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 108 }); room = Core.configureOnlineMatch(room, { playerIndex: 0, settings: { gameType: "country", rounds: 5 }, expectedVersion: room.stateVersion, now: 109 }); assert.equal(room.status, "waiting"); assert.equal(room.settings.gameType, "country"); assert.ok(room.players.every((player) => !player.ready)); });
test("oda puanları yeni oyunda sıfırlanmaz ve birikerek devam eder", () => { let room = playingRoom(); room = Core.submitOnlineAnswer(room, { playerIndex: 0, questionId: "q1", selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 106 }); room = Core.submitOnlineAnswer(room, { playerIndex: 1, questionId: "q1", selectedPlayerId: 11, expectedVersion: room.stateVersion, now: 107 }); room = Core.finishOnlineGame(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 108 }); assert.deepEqual(room.totalScores, [1, 0]); room = Core.configureOnlineMatch(room, { playerIndex: 0, settings: { gameType: "country" }, expectedVersion: room.stateVersion, now: 109 }); room = Core.setOnlineReady(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 110 }); room = Core.setOnlineReady(room, { playerIndex: 1, expectedVersion: room.stateVersion, now: 111 }); room = Core.startOnlineGame(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 112 }); assert.deepEqual(room.scores, [1, 0]); });
test("özel oyunun son soru paketi sonraki maç için saklanır", () => { let room = playingRoom(); room = { ...room, question: null, revealUntil: null }; room = Core.syncOnlineModeState(room, { playerIndex: 0, modeState: { kind: "randomFive", value: { round: 5, finished: true, setIds: [[1, 2, 3, 4, 5]] } }, currentTurn: 0, scores: room.scores, expectedVersion: room.stateVersion, now: 106 }); room = Core.finishOnlineGame(room, { playerIndex: 0, expectedVersion: room.stateVersion, now: 107 }); assert.deepEqual(room.settings.lastModeState.value.setIds, [[1, 2, 3, 4, 5]]); });
test("güncel olmayan sürüm yeni state'i ezemez", () => assert.throws(() => Core.setOnlineReady(playingRoom(), { playerIndex: 0, expectedVersion: 1, now: 106 }), /STALE_STATE/));
test("bağlantı sonrası güncel state yeniden alınabilir", () => { const room = playingRoom(); const offline = Core.updateConnection(room, { playerIndex: 1, connected: false, expectedVersion: room.stateVersion, now: 106 }); const back = Core.updateConnection(offline, { playerIndex: 1, connected: true, expectedVersion: offline.stateVersion, now: 107 }); assert.equal(back.players[1].connected, true); });
test("süresi dolmuş oda kullanılamaz", () => { const room = Core.createOnlineRoom({ settings: {}, now: 0 }); assert.equal(Core.isRoomExpired(room, Core.ROOM_TTL_MS), true); });
test("özel oyun sırası tek sürümlü hamleyle yalnız bir kez ilerler", () => { let room = playingRoom(); room = { ...room, question: null }; room = Core.syncOnlineModeState(room, { playerIndex: 0, modeState: { kind: "randomFive", value: { round: 0, guesses: [10] } }, currentTurn: 1, scores: [0, 0], expectedVersion: room.stateVersion, now: 106 }); assert.equal(room.currentTurn, 1); assert.throws(() => Core.syncOnlineModeState(room, { playerIndex: 0, modeState: { kind: "randomFive", value: { round: 0, guesses: [10, 10] } }, currentTurn: 1, scores: [9, 0], expectedVersion: room.stateVersion, now: 107 }), /NOT_YOUR_TURN/); });
test("süre dolunca cevap vermeyenler timeout olur ve tur açıklanır", () => { let room = playingRoom(); room.question.deadlineAt = 200; room = Core.submitOnlineAnswer(room, { playerIndex: 0, questionId: "q1", selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 150 }); room = Core.timeoutOnlineQuestion(room, { questionId: "q1", expectedVersion: room.stateVersion, now: 200 }); assert.equal(room.roundAnswers[0].result, "correct"); assert.equal(room.roundAnswers[1].result, "timeout"); assert.equal(room.answerResult, "revealed"); assert.equal(room.revealUntil, 2200); });
test("süre dolmadan timeout işlemi yapılamaz", () => { const room = playingRoom(); room.question.deadlineAt = 500; assert.throws(() => Core.timeoutOnlineQuestion(room, { questionId: "q1", expectedVersion: room.stateVersion, now: 499 }), /TIME_REMAINING/); });
test("Rastgele Beşler iki oyuncunun tahminini bekleyip birlikte açıklar", () => { let room = playingRoom(); room = { ...room, question: null }; room = Core.syncOnlineModeState(room, { playerIndex: 0, modeState: { kind: "randomFive", value: { round: 0, guessIds: {}, revealUntil: null } }, currentTurn: 0, scores: [0, 0], expectedVersion: room.stateVersion, now: 106 }); room = Core.submitOnlineSpecialGuess(room, { playerIndex: 0, kind: "randomFive", step: 0, selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 107 }); assert.equal(room.modeState.value.revealUntil, null); room = Core.submitOnlineSpecialGuess(room, { playerIndex: 1, kind: "randomFive", step: 0, selectedPlayerId: 11, expectedVersion: room.stateVersion, now: 108 }); assert.deepEqual(room.modeState.value.guessIds, { 0: 10, 1: 11 }); assert.equal(room.modeState.value.revealUntil, 2108); });
test("Rastgele Beşler aynı oyuncunun ikinci tahminini engeller", () => { let room = playingRoom(); room = { ...room, question: null }; room = Core.syncOnlineModeState(room, { playerIndex: 0, modeState: { kind: "randomFive", value: { round: 0, guessIds: {} } }, currentTurn: 0, scores: [0, 0], expectedVersion: room.stateVersion, now: 106 }); room = Core.submitOnlineSpecialGuess(room, { playerIndex: 0, kind: "randomFive", step: 0, selectedPlayerId: 10, expectedVersion: room.stateVersion, now: 107 }); assert.throws(() => Core.submitOnlineSpecialGuess(room, { playerIndex: 0, kind: "randomFive", step: 0, selectedPlayerId: 11, expectedVersion: room.stateVersion, now: 108 }), /SPECIAL_GUESS_ALREADY_SUBMITTED/); });
