'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
test('web verisinde Cristiano Ronaldo kariyerinin beş A takım kulübü bulunur',()=>{const root=path.join(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'data','web-data.json'),'utf8')),player=data.players.find(p=>p.id===8198),names=player.clubIds.map(id=>data.clubs.find(c=>c.id===id)?.name);for(const club of ['Sporting CP','Manchester United','Real Madrid','Juventus FC','Al-Nassr Football Club'])assert.ok(names.includes(club),club);});
test('web istatistikleri kaynak maç, gol, asist ve milli takım alanlarını içerir',()=>{const data=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','web-data.json'),'utf8')),player=data.players.find(p=>p.id===8198);assert.ok(player.appearances>400);assert.ok(player.goals>300);assert.ok(player.assists>50);assert.ok(player.nationalCaps>200);assert.ok(player.nationalGoals>100);assert.equal(player.nationality,'Portekiz');assert.ok(data.clubs.every(c=>!['England','Scotland'].includes(c.country)));});
test('web oyuncuları kart ve piyasa değeri alanlarını taşır',()=>{const data=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','web-data.json'),'utf8'));assert.equal(data.version,6);assert.ok(data.statistics.unavailableFields.includes('nationalAssists'));for(const player of data.players){assert.ok(Number.isInteger(player.yellowCards)&&player.yellowCards>=0);assert.ok(Number.isInteger(player.redCards)&&player.redCards>=0);assert.ok(player.marketValueInEur===null||Number.isFinite(player.marketValueInEur));assert.ok(player.highestMarketValueInEur===null||Number.isFinite(player.highestMarketValueInEur));assert.equal(player.nationalAssists,null);}});
test('tam kariyer kontrol oyuncuları doğru aralıkta ve gol lideri Ronaldo',()=>{const data=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','web-data.json'),'utf8')),ronaldo=data.players.find(p=>p.id===8198),lewandowski=data.players.find(p=>p.id===38253);assert.ok(lewandowski.appearances>=860);assert.ok(lewandowski.goals>=625);assert.ok(ronaldo.goals>lewandowski.goals);assert.equal([...data.players].sort((a,b)=>b.goals-a.goals)[0].id,8198);});
test('her oyuncunun istatistik kapsamı açıkça işaretlidir',()=>{const data=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','web-data.json'),'utf8'));assert.ok(data.players.every(p=>typeof p.statisticsComplete==='boolean'&&p.statisticsCoverage));assert.ok(data.players.filter(p=>p.statisticsComplete).length>22000);});
test('Türkiye milliyeti tek kanonik filtre değeridir',()=>{const data=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','web-data.json'),'utf8')),values=new Set(data.players.map(p=>p.nationality));assert.ok(values.has('Türkiye'));assert.ok(!values.has('Turkey'));assert.equal([...values].filter(x=>x==='Türkiye').length,1);});
test('web verisi geçerli dokuz kesişimli kulüp ızgarası üretebilir',()=>{const data=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','web-data.json'),'utf8')),active=new Set(data.clubs.filter(c=>c.active).map(c=>c.id)),neighbors=new Map([...active].map(id=>[id,new Set()]));for(const p of data.players){const ids=p.clubIds.filter(id=>active.has(id));for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){neighbors.get(ids[i]).add(ids[j]);neighbors.get(ids[j]).add(ids[i]);}}const rows=[...active].filter(id=>neighbors.get(id).size>=6);assert.ok(rows.some((a,i)=>rows.slice(i+1).some((b,j)=>rows.slice(i+j+2).some(c=>[...neighbors.get(a)].filter(id=>![a,b,c].includes(id)&&neighbors.get(b).has(id)&&neighbors.get(c).has(id)).length>=3))));});
