'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let clubs=[],allClubs=[],results=[],page=1,activeSuggestion=-1;
let game={round:0,total:0,seconds:30,left:30,score:0,timer:null,answers:[],pairs:[],history:[],mode:'clubs'};
const unwrap=async promise=>{const r=await promise;if(!r?.ok)throw Object.assign(new Error(r?.error?.message||'İşlem başarısız.'),{code:r?.error?.code});return r.data};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').replace(/[ıİIşŞğĞüÜöÖçÇ]/g,c=>({'ı':'i','İ':'i','I':'i','ş':'s','Ş':'s','ğ':'g','Ğ':'g','ü':'u','Ü':'u','ö':'o','Ö':'o','ç':'c','Ç':'c'}[c])).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function show(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo(0,0);}
$$('[data-screen]').forEach(b=>b.addEventListener('click',()=>{clearInterval(game.timer);show(b.dataset.screen);}));
function initials(name='?'){return name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
function clubMarkup(c){if(!c)return '<div><h3>Kulüp seçin</h3><p>Arama alanını kullanın</p></div>';return `${c.logo?`<img src="${esc(c.logo)}" alt="" data-fallback="${esc(initials(c.name))}">`:`<div class="fallback">${esc(initials(c.name))}</div>`}<div><h3>${esc(c.name)}</h3><p>${esc(c.league)} • ${esc(c.country)}</p></div>`;}
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'){const d=document.createElement('div');d.className=e.target.closest('.player')?'avatar':'fallback';d.textContent=e.target.dataset.fallback||'';d.setAttribute('aria-hidden','true');e.target.replaceWith(d);}},true);
function selected(input){return allClubs.find(c=>String(c.id)===input.dataset.id);}
function renderPreviews(){const a=selected($('#clubA')),b=selected($('#clubB'));$('#previewA').innerHTML=clubMarkup(a);$('#previewB').innerHTML=clubMarkup(b);$('#listPlayers').disabled=!a||!b||a.id===b.id;}
function filteredClubs(input,showAll=false){const country=$('#countryFilter').value,league=$('#leagueFilter').value,q=showAll?'':norm(input.value);return allClubs.filter(c=>(!country||c.country===country)&&(!league||c.league===league)&&(!q||norm(c.name).includes(q)||norm(c.slug).includes(q)));}
function closeClubLists(except){for(const id of ['clubA','clubB']){if(id!==except){$('#'+id).setAttribute('aria-expanded','false');$('#'+id).closest('.club-combobox').querySelector('.club-options').classList.remove('open');}}}
function renderClubOptions(id,open=true,showAll=false){const input=$('#'+id),list=input.closest('.club-combobox').querySelector('.club-options'),other=selected($('#'+(id==='clubA'?'clubB':'clubA')));clubs=filteredClubs(input,showAll);list.innerHTML=clubs.map(c=>`<button type="button" class="club-option" role="option" data-id="${c.id}" ${other?.id===c.id?'disabled':''}><b>${esc(c.name)}</b><small>${esc(c.league)} • ${esc(c.country)}</small></button>`).join('')||'<span class="club-empty">Eşleşen kulüp bulunamadı.</span>';list.querySelectorAll('.club-option').forEach(button=>button.onclick=()=>{const club=allClubs.find(c=>String(c.id)===button.dataset.id);input.value=club.name;input.dataset.id=club.id;list.classList.remove('open');input.setAttribute('aria-expanded','false');renderPreviews();});if(open){closeClubLists(id);list.classList.add('open');input.setAttribute('aria-expanded','true');}}
for(const id of ['clubA','clubB']){const input=$('#'+id);input.addEventListener('focus',()=>{renderClubOptions(id,true,true);if(input.dataset.id)setTimeout(()=>input.select(),0);});input.addEventListener('click',()=>{if(input.dataset.id){renderClubOptions(id,true,true);setTimeout(()=>input.select(),0);}});input.addEventListener('input',()=>{delete input.dataset.id;renderClubOptions(id);renderPreviews();});input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.closest('.club-combobox').querySelector('.club-options').classList.remove('open');input.setAttribute('aria-expanded','false');}if(e.key==='ArrowDown'){e.preventDefault();input.closest('.club-combobox').querySelector('.club-option:not([disabled])')?.focus();}});}
$$('.combo-toggle').forEach(button=>button.onclick=()=>{const id=button.dataset.for,input=$('#'+id),list=input.closest('.club-combobox').querySelector('.club-options');if(list.classList.contains('open')){list.classList.remove('open');input.setAttribute('aria-expanded','false');}else{renderClubOptions(id,true,true);input.focus();setTimeout(()=>input.select(),0);}});
document.addEventListener('click',e=>{if(!e.target.closest('.club-combobox'))closeClubLists();});
$('#countryFilter').addEventListener('change',()=>{const country=$('#countryFilter').value;$$('#leagueFilter option').forEach(o=>o.hidden=!!o.value&&o.dataset.country!==country&&!!country);$('#leagueFilter').value='';closeClubLists();});
$('#leagueFilter').addEventListener('change',()=>closeClubLists());
function playerCard(p,clubsPair){return `<article class="player">${p.photo?`<img src="${esc(p.photo)}" alt="" loading="lazy" data-fallback="${esc(initials(p.name))}">`:`<div class="avatar">${esc(initials(p.name))}</div>`}<div><strong>${esc(p.name)}</strong><small>${esc(clubsPair[0].name)}: ${esc(p.periodsA||'dönem bilinmiyor')}</small><small>${esc(clubsPair[1].name)}: ${esc(p.periodsB||'dönem bilinmiyor')}</small>${p.verified?'':'<small class="candidate">A takım teyidi bekliyor</small>'}</div></article>`;}
let resultClubs=[];
function renderResults(){let list=results.filter(p=>norm(p.name).includes(norm($('#resultSearch').value)));if($('#resultSort').value==='start')list.sort((a,b)=>String(a.periodsA).localeCompare(String(b.periodsA)));else list.sort((a,b)=>a.name.localeCompare(b.name,'tr'));const size=24,pages=Math.max(1,Math.ceil(list.length/size));page=Math.min(page,pages);const shown=list.slice((page-1)*size,page*size);$('#playerGrid').innerHTML=shown.map(p=>playerCard(p,resultClubs)).join('')||'<div class="empty">Aramanızla eşleşen oyuncu yok.</div>';$('#pageInfo').textContent=`${page} / ${pages}`;$('#prevPage').disabled=page<=1;$('#nextPage').disabled=page>=pages;}
$('#resultSearch').addEventListener('input',()=>{page=1;renderResults();});$('#resultSort').addEventListener('change',renderResults);$('#prevPage').onclick=()=>{page--;renderResults();};$('#nextPage').onclick=()=>{page++;renderResults();};
$('#listPlayers').addEventListener('click',async()=>{const a=selected($('#clubA')),b=selected($('#clubB'));if(!a||!b)return;if(a.id===b.id){$('#compareMessage').textContent='Aynı kulüp iki kez seçilemez.';return;}const btn=$('#listPlayers');btn.disabled=true;btn.classList.add('loading-button');$('#compareMessage').textContent='Yerel veritabanı sorgulanıyor…';try{const r=await unwrap(window.ikiForma.commonPlayers({clubA:a.id,clubB:b.id}));results=r.players;resultClubs=r.clubs;page=1;$('#results').classList.remove('hidden');$('#resultTitle').textContent=`${r.clubs[0].name} ↔ ${r.clubs[1].name}`;$('#resultMeta').textContent=`Yerel SQLite • ${r.verifiedCount} A takım doğrulanmış • ${r.candidateCount} açık veri adayı`;$('#resultCount').textContent=`${r.count} oyuncu`;$('#compareMessage').textContent=r.count?'':'Bu iki kulüp için ortak oyuncu kaydı bulunamadı.';renderResults();}catch(e){$('#results').classList.add('hidden');$('#compareMessage').textContent=e.message;}finally{btn.classList.remove('loading-button');renderPreviews();}});
$('#updateData').onclick=async()=>{try{const s=await unwrap(window.ikiForma.dataStatus());$('#compareMessage').textContent=`Veri ${s.version}: ${s.counts.clubs} kulüp, ${s.counts.players} oyuncu, ${s.counts.player_clubs} kariyer kaydı (${s.counts.verifiedFirstTeam} A takım doğrulanmış).`;}catch(e){$('#compareMessage').textContent=e.message;}};
async function countdown(){const box=$('#countdown'),screen=$('#game');screen.classList.add('counting');box.classList.remove('hidden');for(const n of [3,2,1]){box.textContent=n;await new Promise(r=>setTimeout(r,700));}box.textContent='BAŞLA!';await new Promise(r=>setTimeout(r,400));box.classList.add('hidden');screen.classList.remove('counting');}
function tick(){game.left--;$('#timer').textContent=`${Math.max(0,game.left)} sn`;$('#timebar').style.width=`${Math.max(0,game.left/game.seconds*100)}%`;if(game.left<=0)finishRound(null,'Süre doldu');}
function finishRound(player,label){clearInterval(game.timer);if(player){const bonus=Math.max(10,game.left*3);game.score+=bonus;$('#score').textContent=game.score;label=`Doğru: ${player.name} (+${bonus})`;}game.history.push({clubs:game.current.clubs.map(c=>c.name).join(' – '),result:label,answers:game.answers.map(x=>x.name).sort((a,b)=>a.localeCompare(b,'tr'))});$('#gameMessage').textContent=label;setTimeout(nextRound,900);}
function choosePlayer(p){if(game.answers.some(a=>a.id===p.id))finishRound(p,'');else $('#gameMessage').textContent='Bu oyuncu iki kulübün ortak kariyerinde bulunmuyor.';$('#suggestions').innerHTML='';}
async function nextRound(){clearInterval(game.timer);if(game.round>=game.total){$('#finalScore').textContent=`Toplam skor: ${game.score}`;$('#roundResults').innerHTML=game.history.map((x,i)=>`<div><b>${i+1}. ${esc(x.clubs)}</b><span>${esc(x.result)}</span><span><strong>Geçerli cevapların tamamı (${x.answers.length}):</strong> ${esc(x.answers.join(' • ')||'Cevap bulunamadı')}</span></div>`).join('');show('final');return;}game.round++;$('#round').textContent=`${game.round}/${game.total}`;$('#playerInput').value='';$('#suggestions').innerHTML='';$('#gameMessage').textContent='Geçerli eşleşme hazırlanıyor…';try{const difficulty=game.mode==='country'?$('#countryDifficulty').value:$('#difficulty').value;game.current=await unwrap(game.mode==='country'?window.ikiForma.createCountryRound({excludedPairs:game.pairs,difficulty}):window.ikiForma.createRound({excludedPairs:game.pairs,difficulty}));game.pairs.push(game.current.pairKey);game.answers=game.current.players;$('#gameClubA').innerHTML=clubMarkup(game.current.clubs[0]);$('#gameClubB').innerHTML=clubMarkup(game.current.clubs[1]);await countdown();game.left=game.seconds;$('#timer').textContent=`${game.left} sn`;$('#timebar').style.width='100%';$('#gameMessage').textContent=`${game.current.difficulty} tur • ${game.mode==='country'?'ülke vatandaşı ve kulüp oyuncusunu':'ortak futbolcuyu'} bul`;game.timer=setInterval(tick,1000);$('#playerInput').focus();}catch(e){$('#gameMessage').textContent=e.message;setTimeout(()=>show('home'),1800);}}
$('#playerInput').addEventListener('input',async e=>{const q=e.target.value.trim();activeSuggestion=-1;if(q.length<2){$('#suggestions').innerHTML='';return;}try{const hits=await unwrap(window.ikiForma.searchPlayers(q,12));$('#suggestions').innerHTML=hits.map(p=>`<button role="option" data-id="${p.id}">${p.photo?`<img src="${esc(p.photo)}" alt="" data-fallback="${esc(initials(p.name))}">`:`<span class="suggestion-avatar">${esc(initials(p.name))}</span>`}<span class="suggestion-info"><b>${esc(p.name)}</b><small>${p.clubCount?`${p.clubCount} kulüp • ${esc(p.clubs)}`:'Kulüp geçmişi bulunamadı'}</small></span></button>`).join('');$$('#suggestions button').forEach((b,i)=>b.onclick=()=>choosePlayer(hits[i]));}catch{$('#suggestions').innerHTML='';}});
$('#playerInput').addEventListener('keydown',e=>{const opts=$$('#suggestions button');if((e.key==='ArrowDown'||e.key==='ArrowUp')&&opts.length){e.preventDefault();activeSuggestion=(activeSuggestion+(e.key==='ArrowDown'?1:-1)+opts.length)%opts.length;opts.forEach((o,i)=>o.classList.toggle('active',i===activeSuggestion));}else if(e.key==='Enter'){e.preventDefault();if(activeSuggestion>=0&&opts[activeSuggestion])opts[activeSuggestion].click();else{const p=game.answers.find(x=>norm(x.name)===norm(e.target.value.trim()));if(p)choosePlayer(p);else $('#gameMessage').textContent='Geçerli bir ortak oyuncu seçin.';}}});
$('#passBtn').onclick=()=>finishRound(null,'Pas');
$('#startGame').onclick=()=>{game={...game,mode:'clubs',total:+$('#roundCount').value,seconds:+$('#roundSeconds').value,round:0,score:0,pairs:[],history:[]};$('#score').textContent='0';show('game');nextRound();};
$('#startCountryGame').onclick=()=>{game={...game,mode:'country',total:+$('#countryRoundCount').value,seconds:+$('#countryRoundSeconds').value,round:0,score:0,pairs:[],history:[]};$('#score').textContent='0';show('game');nextRound();};
let gridState={data:null,marks:Array(9).fill(null),names:Array(9).fill(null),turn:'X',selected:null,over:false,xScore:0,oScore:0};
const winLines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function gridClub(c){return `${c.logo?`<img src="${esc(c.logo)}" alt="">`:`<span class="fallback">${esc(initials(c.name))}</span>`}<b>${esc(c.name)}</b>`;}
function renderGrid(){if(!gridState.data)return;let html='<div class="grid-corner"></div>';for(const c of gridState.data.cols)html+=`<div class="grid-club">${gridClub(c)}</div>`;for(let r=0;r<3;r++){html+=`<div class="grid-club">${gridClub(gridState.data.rows[r])}</div>`;for(let c=0;c<3;c++){const i=r*3+c,m=gridState.marks[i];html+=`<button class="grid-cell ${m?'taken '+m.toLowerCase():''}" data-cell="${i}" ${m||gridState.over?'disabled':''}>${m?`<span><span class="mark">${m}</span><small>${esc(gridState.names[i])}</small></span>`:'?'}</button>`;}}$('#footballGrid').innerHTML=html;$$('.grid-cell:not(.taken)').forEach(b=>b.onclick=()=>openGridEntry(+b.dataset.cell));$('#gridTurn').textContent=`${gridState.over?'Oyun bitti':`Sıra: ${gridState.turn}`} • X ${gridState.xScore} / O ${gridState.oScore}`;$('#score').textContent=`${gridState.xScore}-${gridState.oScore}`;}
function cellAnswers(index){return gridState.data.cells[index].answers;}
function openGridEntry(index){if(gridState.over||($('#gridMode').value==='solo'&&gridState.turn==='O'))return;gridState.selected=index;const r=Math.floor(index/3),c=index%3;$('#gridPrompt').textContent=`${gridState.data.rows[r].name} × ${gridState.data.cols[c].name}`;$('#gridPlayerInput').value='';$('#gridSuggestions').innerHTML='';$('#gridEntry').classList.remove('hidden');$('#gridPlayerInput').focus();}
function finishGridMove(index,player,mark=gridState.turn){gridState.marks[index]=mark;gridState.names[index]=player.name;if(mark==='X')gridState.xScore+=100;else gridState.oScore+=100;const win=winLines.find(line=>line.every(i=>gridState.marks[i]===mark));if(win){if(mark==='X')gridState.xScore+=300;else gridState.oScore+=300;gridState.over=true;$('#gridMessage').textContent=`${mark} kazandı: ${player.name} (+300 bonus)`;}else if(gridState.marks.every(Boolean)){gridState.over=true;$('#gridMessage').textContent='Berabere!';}else gridState.turn=mark==='X'?'O':'X';renderGrid();if(!gridState.over&&$('#gridMode').value==='solo'&&gridState.turn==='O')setTimeout(computerGridMove,700);}
function submitGridPlayer(player){const index=gridState.selected,valid=cellAnswers(index).find(a=>a.id===player.id||norm(a.name)===norm(player.name));if(!valid){const failedTurn=gridState.turn;$('#gridMessage').textContent=`${player.name} geçerli değil; ${failedTurn} sırasını kaybetti.`;$('#gridEntry').classList.add('hidden');gridState.turn=failedTurn==='X'?'O':'X';renderGrid();if($('#gridMode').value==='solo'&&gridState.turn==='O')setTimeout(computerGridMove,700);return;}$('#gridEntry').classList.add('hidden');$('#gridMessage').textContent=`${gridState.turn}: ${valid.name}`;finishGridMove(index,valid);}
$('#gridPlayerInput').addEventListener('input',async e=>{const q=e.target.value.trim();if(q.length<2){$('#gridSuggestions').innerHTML='';return;}try{const hits=await unwrap(window.ikiForma.searchPlayers(q,10));$('#gridSuggestions').innerHTML=hits.map((p,i)=>`<button data-grid-hit="${i}"><span class="suggestion-info"><b>${esc(p.name)}</b><small>${esc(p.clubs||'Kulüp bilgisi yok')}</small></span></button>`).join('');$$('[data-grid-hit]').forEach(b=>b.onclick=()=>submitGridPlayer(hits[+b.dataset.gridHit]));}catch{$('#gridSuggestions').innerHTML='';}});
$('#gridPlayerInput').addEventListener('keydown',e=>{if(e.key==='Enter'){const answer=cellAnswers(gridState.selected).find(p=>norm(p.name)===norm(e.target.value));if(answer)submitGridPlayer(answer);else $('#gridMessage').textContent='Listeden geçerli bir futbolcu seçin.';}});
$('#cancelGridEntry').onclick=()=>$('#gridEntry').classList.add('hidden');
function computerGridMove(){const free=gridState.marks.map((m,i)=>m?null:i).filter(i=>i!==null);if(!free.length)return;const index=free[Math.floor(Math.random()*free.length)],difficulty=$('#gridDifficulty').value,chance={easy:.45,normal:.68,hard:.88}[difficulty],correct=Math.random()<chance;let player;if(correct)player=cellAnswers(index)[Math.floor(Math.random()*cellAnswers(index).length)];else{const nearby=gridState.data.cells.filter((_,i)=>i!==index&&(Math.floor(i/3)===Math.floor(index/3)||i%3===index%3)).flatMap(c=>c.answers).filter(p=>!cellAnswers(index).some(a=>norm(a.name)===norm(p.name)));player=nearby[Math.floor(Math.random()*nearby.length)]||{name:'Yakın bir oyuncu',id:-1};}if(correct){$('#gridMessage').textContent=`Bilgisayar doğru bildi: ${player.name}`;finishGridMove(index,player,'O');}else{$('#gridMessage').textContent=`Bilgisayar yanlış söyledi: ${player.name}`;gridState.turn='X';renderGrid();}}
async function startGridGame(){show('gridGame');$('#gridMessage').textContent='Geçerli kulüp ızgarası hazırlanıyor…';try{const data=await unwrap(window.ikiForma.createGrid($('#gridDifficulty').value));gridState={data,marks:Array(9).fill(null),names:Array(9).fill(null),turn:'X',selected:null,over:false,xScore:0,oScore:0};$('#score').textContent='0-0';$('#gridMessage').textContent='Bir hücre seçin ve ortak futbolcuyu yazın.';renderGrid();}catch(e){$('#gridMessage').textContent=e.message;}}
$('#startGrid').onclick=startGridGame;$('#newGrid').onclick=startGridGame;$('#gridMode').onchange=()=>$('#gridDifficultyLabel').classList.toggle('hidden',$('#gridMode').value==='duo');
let travelerData=[];function renderTravelers(){const q=norm($('#travelerSearch').value),list=travelerData.filter(p=>!q||norm(p.name).includes(q)||norm(p.clubs).includes(q));$('#travelerCount').textContent=`${list.length} futbolcu`;$('#travelerList').innerHTML=list.map((p,i)=>`<article class="traveler-card"><span class="traveler-rank">${i+1}</span><div class="traveler-name">${p.photo?`<img src="${esc(p.photo)}" alt="">`:'<span class="avatar" aria-hidden="true"></span>'}<b>${esc(p.name)}</b></div><div class="traveler-clubs">${esc(String(p.clubs||'').replaceAll(',', ' • '))}</div><span class="traveler-total">${p.clubCount} kulüp</span></article>`).join('');}
async function loadTravelers(){if(travelerData.length)return renderTravelers();$('#travelerList').innerHTML='<div class="empty">Sıralama hazırlanıyor…</div>';try{travelerData=await unwrap(window.ikiForma.travelers(150));renderTravelers();}catch(e){$('#travelerList').innerHTML=`<div class="empty">${esc(e.message)}</div>`;}}
$('#travelerSearch').oninput=renderTravelers;$$('[data-screen="travelers"]').forEach(b=>b.addEventListener('click',loadTravelers));
let catalogPage=1,catalogTimer=null;
async function loadCatalog(reset=false){if(reset)catalogPage=1;$('#catalogList').innerHTML='<div class="empty">Futbolcular yükleniyor…</div>';try{const data=await unwrap(window.ikiForma.playerCatalog({query:$('#catalogSearch').value.trim(),clubId:$('#catalogClub').value,nationality:$('#catalogNationality').value,sort:$('#catalogSort').value,page:catalogPage,pageSize:100}));catalogPage=data.page;$('#catalogCount').textContent=`${data.total} futbolcu`;$('#catalogPage').textContent=`${data.page} / ${data.pages}`;$('#catalogPrev').disabled=data.page<=1;$('#catalogNext').disabled=data.page>=data.pages;$('#catalogList').innerHTML=data.players.map((p,i)=>`<article class="traveler-card"><span class="traveler-rank">${(data.page-1)*data.pageSize+i+1}</span><div class="traveler-name">${p.photo?`<img src="${esc(p.photo)}" alt="">`:'<span class="avatar" aria-hidden="true"></span>'}<span><b>${esc(p.name)}</b><small>${esc(p.nationality||'Milliyet bilinmiyor')}${p.birthDate?` • ${esc(p.birthDate.slice(0,4))}`:''}</small></span></div><div class="traveler-clubs">${esc(p.clubs||'Kulüp bilgisi yok')}</div><span class="traveler-total">${p.clubCount} kulüp<br><small>${p.appearances} maç</small></span></article>`).join('')||'<div class="empty">Filtrelerle eşleşen futbolcu yok.</div>';}catch(e){$('#catalogList').innerHTML=`<div class="empty">${esc(e.message)}</div>`;}}
async function openCatalog(){if(!$('#catalogNationality').dataset.loaded){const filters=await unwrap(window.ikiForma.playerFilters());$('#catalogNationality').insertAdjacentHTML('beforeend',filters.nationalities.map(x=>`<option value="${esc(x.nationality)}">${esc(x.nationality)} (${x.count})</option>`).join(''));$('#catalogClub').insertAdjacentHTML('beforeend',allClubs.map(c=>`<option value="${c.id}">${esc(c.name)} • ${esc(c.league)}</option>`).join(''));$('#catalogNationality').dataset.loaded='1';}loadCatalog(true);}
$$('[data-screen="playerCatalog"]').forEach(b=>b.addEventListener('click',openCatalog));$('#catalogSearch').oninput=()=>{clearTimeout(catalogTimer);catalogTimer=setTimeout(()=>loadCatalog(true),250);};$('#catalogClub').onchange=()=>loadCatalog(true);$('#catalogNationality').onchange=()=>loadCatalog(true);$('#catalogSort').onchange=()=>loadCatalog(true);$('#catalogPrev').onclick=()=>{catalogPage--;loadCatalog();};$('#catalogNext').onclick=()=>{catalogPage++;loadCatalog();};
(async()=>{try{[allClubs]=await Promise.all([unwrap(window.ikiForma.listClubs({})),unwrap(window.ikiForma.clubFilters()).then(f=>{for(const c of f.countries)$('#countryFilter').insertAdjacentHTML('beforeend',`<option>${esc(c)}</option>`);for(const l of f.leagues)$('#leagueFilter').insertAdjacentHTML('beforeend',`<option data-country="${esc(l.country)}">${esc(l.league)}</option>`);} )]);renderPreviews();const s=await unwrap(window.ikiForma.dataStatus());$('#dataBadge').textContent=`Çevrimdışı hazır • ${s.counts.clubs} kulüp • ${s.counts.players} oyuncu`; }catch(e){$('#dataBadge').textContent=e.message;}})();
