'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').toLowerCase(),initials=s=>String(s).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
let DATA,clubs=[],players=[],clubMap,clubPlayers=new Map(),catalogPage=1,game={},timer,grid={};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}
function show(id){clearInterval(timer);$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));scrollTo({top:0,behavior:'smooth'});if(id==='catalog')renderCatalog(true);if(id==='travelers')renderTravelers();if(id==='grid')newGrid();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});
function logo(c){return c?.logo?`<img src="${esc(c.logo)}" alt="${esc(c.name)} logosu" loading="lazy">`:`<span class="club-logo">${esc(initials(c?.name||''))}</span>`}
function side(c){return `${logo(c)}<div><h2>${esc(c.name)}</h2><p>${esc(c.league||c.country||'')}</p></div>`}
function person(p){return p.photo?`<img src="${esc(p.photo)}" alt="" loading="lazy">`:'<span class="avatar"></span>'}
function namesForClubs(ids){const set=ids.map(id=>clubPlayers.get(+id)||[]);return (set[0]||[]).filter(p=>set.slice(1).every(list=>list.some(x=>x.id===p.id)))}
function setupScreen(id,title,description,mode){$(id).innerHTML=`<button class="back" data-view="home">← Ana sayfa</button><div class="surface"><span class="kicker">OYUN AYARLARI</span><h2>${title}</h2><p>${description}</p><label>Tur sayısı<select class="rounds"><option>3</option><option selected>5</option><option>10</option><option>15</option></select></label><label>Tur süresi<select class="seconds"><option>15</option><option selected>30</option><option>45</option></select></label><label>Zorluk<select class="difficulty"><option value="normal">Normal</option><option value="easy">Kolay</option><option value="hard">Zor</option></select></label><button class="cta start">Oyunu başlat →</button></div>`;$(id).querySelector('.start').onclick=()=>startGame(mode,$(id));}
function buildPairs(mode,difficulty){const pairs=[];if(mode==='clubs'){const active=clubs.filter(c=>c.active);for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){const answers=namesForClubs([active[i].id,active[j].id]);if(answers.length&&(difficulty!=='easy'||answers.length>=6)&&(difficulty!=='hard'||answers.length<=3))pairs.push({a:active[i],b:active[j],answers,key:`${active[i].id}:${active[j].id}`});}}else{for(const c of clubs.filter(x=>x.active)){const grouped=new Map();for(const p of clubPlayers.get(c.id)||[]){if(!p.nationality)continue;if(!grouped.has(p.nationality))grouped.set(p.nationality,[]);grouped.get(p.nationality).push(p)}for(const [nationality,list] of grouped){if((difficulty==='easy'&&list.length<6)||(difficulty==='normal'&&list.length<2)||(difficulty==='hard'&&list.length>2))continue;pairs.push({a:{name:nationality,league:'Vatandaşlık'},b:c,answers:list,key:`${nationality}:${c.id}`});}}}return pairs.sort(()=>Math.random()-.5)}
function startGame(mode,screen){const difficulty=screen.querySelector('.difficulty').value;game={mode,round:0,total:+screen.querySelector('.rounds').value,seconds:+screen.querySelector('.seconds').value,score:0,pairs:buildPairs(mode,difficulty),history:[]};$('#score').textContent=0;show('game');nextRound()}
function nextRound(){clearInterval(timer);if(game.round>=game.total||!game.pairs.length)return finishGame();const current=game.pairs.shift();game.current=current;game.round++;game.left=game.seconds;$('#gameRound').textContent=`Tur ${game.round}/${game.total}`;$('#sideA').innerHTML=side(current.a);$('#sideB').innerHTML=side(current.b);$('#answerInput').value='';$('#answerSuggestions').innerHTML='';$('#gameMessage').textContent='Ortak futbolcuyu bul';tick();timer=setInterval(()=>{game.left--;tick();if(game.left<=0)endRound(null,'Süre doldu')},1000);$('#answerInput').focus()}
function tick(){$('#timer').textContent=`${game.left} sn`;$('#timebar').style.width=`${Math.max(0,game.left/game.seconds*100)}%`}
function endRound(player,result){clearInterval(timer);if(player){const points=Math.max(10,game.left*3);game.score+=points;$('#score').textContent=game.score;result=`Doğru: ${player.name} (+${points})`}game.history.push({pair:`${game.current.a.name} — ${game.current.b.name}`,result,answers:game.current.answers.map(x=>x.name).sort((a,b)=>a.localeCompare(b,'tr'))});$('#gameMessage').textContent=result;setTimeout(nextRound,750)}
function finishGame(){$('#finalScore').textContent=`Toplam skor: ${game.score}`;$('#roundResults').innerHTML=game.history.map((x,i)=>`<article><b>${i+1}. ${esc(x.pair)}</b><small>${esc(x.result)}</small><small><strong>Tüm cevaplar (${x.answers.length}):</strong> ${esc(x.answers.join(' • '))}</small></article>`).join('');show('results')}
$('#answerInput').oninput=e=>{const q=norm(e.target.value);if(q.length<2)return $('#answerSuggestions').innerHTML='';const hits=players.filter(p=>norm(p.name).includes(q)).slice(0,10);$('#answerSuggestions').innerHTML=hits.map(p=>`<button data-id="${p.id}">${esc(p.name)} <small>• ${esc(p.nationality||'')}</small></button>`).join('');$$('#answerSuggestions button').forEach(b=>b.onclick=()=>{const p=players.find(x=>x.id===+b.dataset.id),valid=game.current.answers.some(x=>x.id===p.id);if(valid)endRound(p,'');else{$('#gameMessage').textContent='Bu oyuncu eşleşme için geçerli değil.';$('#answerSuggestions').innerHTML='';}})};
$('#answerInput').onkeydown=e=>{if(e.key==='Enter'){const p=game.current?.answers.find(x=>norm(x.name)===norm(e.target.value));if(p)endRound(p,'');else $('#gameMessage').textContent='Listeden geçerli bir futbolcu seçin.'}};$('#pass').onclick=()=>endRound(null,'Pas');
function playerRow(p,i,showAppearances=true){const career=p.clubIds.map(id=>clubMap.get(id)?.name).filter(Boolean).sort().join(' • ');return `<article class="player-row"><span class="rank">${i}</span><div class="person">${person(p)}<span><b>${esc(p.name)}</b><small>${esc(p.nationality||'Milliyet bilinmiyor')}${p.birthDate?` • ${p.birthDate.slice(0,4)}`:''}</small></span></div><div class="clubs">${esc(career)}</div><span class="badge">${showAppearances?`${p.appearances} maç • `:''}${p.clubIds.length} kulüp</span></article>`}
function renderCatalog(reset=false){if(reset)catalogPage=1;const q=norm($('#catalogSearch').value),club=+$('#catalogClub').value,nation=$('#catalogNationality').value,sort=$('#catalogSort').value;let list=players.filter(p=>(!q||norm(p.name).includes(q))&&(!club||p.clubIds.includes(club))&&(!nation||p.nationality===nation));list.sort(sort==='name'?(a,b)=>a.name.localeCompare(b.name,'tr'):sort==='clubs'?(a,b)=>b.clubIds.length-a.clubIds.length||b.appearances-a.appearances:sort==='birth'?(a,b)=>String(b.birthDate).localeCompare(String(a.birthDate)): (a,b)=>b.appearances-a.appearances||b.clubIds.length-a.clubIds.length);const pages=Math.max(1,Math.ceil(list.length/100));catalogPage=Math.min(catalogPage,pages);const page=list.slice((catalogPage-1)*100,catalogPage*100);$('#catalogCount').textContent=`${list.length.toLocaleString('tr-TR')} futbolcu`;$('#catalogList').innerHTML=page.map((p,i)=>playerRow(p,(catalogPage-1)*100+i+1)).join('')||'<p class="message">Eşleşen futbolcu bulunamadı.</p>';$('#catalogPage').textContent=`${catalogPage} / ${pages}`;$('#catalogPrev').disabled=catalogPage===1;$('#catalogNext').disabled=catalogPage===pages}
let searchTimer;$('#catalogSearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>renderCatalog(true),180)};for(const id of ['catalogClub','catalogNationality','catalogSort'])$('#'+id).onchange=()=>renderCatalog(true);$('#catalogPrev').onclick=()=>{catalogPage--;renderCatalog()};$('#catalogNext').onclick=()=>{catalogPage++;renderCatalog()};
function renderTravelers(){const q=norm($('#travelerSearch').value);const list=players.filter(p=>p.clubIds.length>1&&(!q||norm(p.name).includes(q)||p.clubIds.some(id=>norm(clubMap.get(id)?.name).includes(q)))).sort((a,b)=>b.clubIds.length-a.clubIds.length||b.appearances-a.appearances).slice(0,250);$('#travelerList').innerHTML=list.map((p,i)=>playerRow(p,i+1,false)).join('')}
$('#travelerSearch').oninput=renderTravelers;
function compare(){const a=+$('#compareA').value,b=+$('#compareB').value;if(a===b)return $('#compareMessage').textContent='İki farklı kulüp seçin.';const list=namesForClubs([a,b]);$('#compareMessage').textContent=`${list.length} ortak futbolcu`;$('#compareList').innerHTML=list.sort((x,y)=>x.name.localeCompare(y.name,'tr')).map((p,i)=>playerRow(p,i+1)).join('')||'<p class="message">Ortak futbolcu bulunamadı.</p>'}$('#compareButton').onclick=compare;
function newGrid(){const active=clubs.filter(c=>c.active);for(let tries=0;tries<1000;tries++){const rows=active.sort(()=>Math.random()-.5).slice(0,3),cols=active.filter(c=>!rows.includes(c)).sort(()=>Math.random()-.5).slice(0,3);if(rows.every(r=>cols.every(c=>namesForClubs([r.id,c.id]).length))){grid={rows,cols,marks:Array(9).fill(null)};renderGrid();return}}$('#gridMessage').textContent='Uygun ızgara üretilemedi.'}
function renderGrid(){let html='<div class="grid-head"></div>'+grid.cols.map(c=>`<div class="grid-head">${logo(c)}<small>${esc(c.name)}</small></div>`).join('');grid.rows.forEach((r,ri)=>{html+=`<div class="grid-head">${logo(r)}<small>${esc(r.name)}</small></div>`;grid.cols.forEach((c,ci)=>{const i=ri*3+ci;html+=`<button class="grid-cell" data-cell="${i}" ${grid.marks[i]?'disabled':''}>${grid.marks[i]?`✓<small>${esc(grid.marks[i])}</small>`:'?'}</button>`})});$('#gridBoard').innerHTML=html;$$('[data-cell]').forEach(b=>b.onclick=()=>{const i=+b.dataset.cell,r=grid.rows[Math.floor(i/3)],c=grid.cols[i%3],answer=prompt(`${r.name} ve ${c.name} kulüplerinde oynamış futbolcu:`);const p=namesForClubs([r.id,c.id]).find(x=>norm(x.name)===norm(answer));if(p){grid.marks[i]=p.name;$('#gridMessage').textContent='Doğru!';renderGrid()}else $('#gridMessage').textContent='Bu isim iki kulüp için geçerli değil.'})}$('#newGrid').onclick=newGrid;
async function init(){try{const response=await fetch('data/web-data.json');if(!response.ok)throw new Error('Veri paketi bulunamadı');DATA=await response.json();clubs=DATA.clubs;players=DATA.players;clubMap=new Map(clubs.map(c=>[c.id,c]));for(const c of clubs)clubPlayers.set(c.id,[]);for(const p of players)for(const id of p.clubIds)clubPlayers.get(id)?.push(p);$('#heroPlayers').textContent=players.length.toLocaleString('tr-TR');$('.hero .kicker').textContent=`${Math.floor(players.length/1000)} BİN+ KARİYER • ÇEVRİMDIŞI VERİ`;const options=clubs.map(c=>`<option value="${c.id}">${esc(c.name)} • ${esc(c.league)}</option>`).join('');$('#catalogClub').insertAdjacentHTML('beforeend',options);$('#compareA').innerHTML=options;$('#compareB').innerHTML=options;$('#compareB').selectedIndex=1;const nations=[...new Set(players.map(p=>p.nationality).filter(Boolean))].sort();$('#catalogNationality').insertAdjacentHTML('beforeend',nations.map(n=>`<option>${esc(n)}</option>`).join(''));setupScreen('#classicSetup','İki Forma','İki kulüpte de A takım forması giymiş futbolcuyu bul.','clubs');setupScreen('#countrySetup','Ülke × Kulüp','Gösterilen ülkenin vatandaşı olup kulüpte oynamış futbolcuyu bul. Milli maç şartı yoktur.','country');show('home')}catch(error){$('#loadingText').textContent=`Site yüklenemedi: ${error.message}`}}init();
